config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'
  devise_for :users
  resources :users
  resources :user_profiles

  resources :categories
  resources :articles do
  collection do
    get 'deleted'
  end
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	acts_as_paranoid
	mount_uploader :featured_image, AvatarUploader
	has_many :article_categories
	has_many :categories, through: :article_categories
	has_many :comments
	belongs_to :user

	validates_presence_of :title, :body, :categories
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article 
	belongs_to :category 
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories


	validates_presence_of :name
	validates_uniqueness_of :name

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article, counter_cache: true
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :articles
	has_one :user_profile
	has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable


end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
	belongs_to :user
	mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :assign_navigation_menu
  before_action :configure_permitted_parameters, if: :devise_controller?


  def assign_navigation_menu
    @categories = Category.all
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	def index
		@articles = Article.order('created_at DESC')
		@popular_posts = Article.order("comments_count DESC")
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user_id = current_user.id
		@article.published_on = DateTime.now
		if @article.save
			redirect_to articles_path, notice: "Successfully Created"
		else
			render action: "new"
		end
	end

	def show
		@article = Article.find(params[:id])
		@users = User.all
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = current_user.articles.find(params[:id])
		if @article.update_attributes(article_params)
			redirect_to article_path(@article), notice: "Succesfully Updated"
		else
			render action: "edit"
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	def deleted
		@deleted = Article.only_deleted
	end

private

	def article_params
		params[:article].permit(:title, :body, :featured_image, :user_id, category_ids: [])
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to categories_path, notice: "Successfully Added"
		else
			render action: "new"
		end
	end

	def show
		@articles = Category.find(params[:id]).articles
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(category_params)
			redirect_to category_path(@category), notice: "Successfully updated"
		else
			render action: "edit"
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path, notice: "Successfully destroyed"
	end

	
private

	def category_params
		params[:category].permit(:name)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def new
		@comment = Comment.new
	end

	def edit
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
	end
	
	def create
		@comment = Comment.new(comment_params)
		@article = Article.find(params[:article_id])
		@comment.article_id = @article.id
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to article_path(@article), notice: "Sucessfully saved"
		else
			render action: "new", notice: "error"
		end
	end

	def update
		@article = Article.find(params[:article_id])
    	@comment = @article.comments.find(params[:id])
   	 	if @comment.update(comment_params)
      		redirect_to article_path(@article)
    	else
      	render action: "edit"
    	end
  	end

private

def comment_params
	params[:comment].permit(:body)
end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
	def index
	end

	def new
		@userprofile = UserProfile.new
	end

	def create
		@userprofile = UserProfile.new(userprofile_params)
		@userprofile.user_id = current_user.id
		if @userprofile.save
			redirect_to articles_path, notice: "Added Successfully"
		else
			render action: "new", notice: "error"
		end
	end

	def show
		@user = UserProfile.find(params[:id])
	end

	def edit
		@userprofile = UserProfile.find(params[:id])
	end

	def update
		@userprofile = UserProfile.find(params[:id])
		if @userprofile.update_attributes(userprofile_params)
			redirect_to user_profile_path, notice: "Successfully Updated"
		else
			render action: "new"
		end
	end

private

	def userprofile_params
		params[:user_profile].permit(:first_name, :last_name, :tagline, :bio, :facebook_id, :twitter_id, :avatar)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
	end

	def new
		@userprofile = UserProfile.new
	end

	def create
		@user_profile = UserProfile.new(userprofile_params)
		if @user_profile.save
			redirect_to users_path, notice: "Added Successfully"
		else
			render action: "new", notice: "error"
		end
	end

	def show
		@user = User.find(params[:id])
		@analyzer = Sentimental.new
		@analyzer.load_defaults
	end

	def edit
		@user = User.new
	end

	def update
		@user_profile = UserProfile.new
		if user_profile.update_attributes(user_profile_params)
			redirect users_path, notice: "Successfully Updated"
		else
			render action: "new"
		end
	end

private

	def userprofile_params
		params["userprofile"].permit(:firstname, :lastname)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@articles = Article.all
  end

  def show
  	@article = Article.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/deleted.html.erb
<div class="row">
  <div class="col-md-7 col-md-offset-1 pull-left">
    <%= render partial: 'layouts/user_settings_menu' %>

    <% if @deleted != nil %>
    <% @deleted.each do |article| %>
    <div class="article">
      <div class="avatar"><%= image_tag article.user.user_profile.avatar.url %></div>
      <div class="user-details">
        <p><%= link_to article.user.username.capitalize, current_user %> in 
          <% article.categories.take(2).each do |category| %>
          <%= link_to category.name, category_path(category) %>
          <% end %>
        </p>
        <p class="sub"><%= article.published_on.strftime("%b %d") if article.published_on? %>
        </p>
      </div>
      <h2><%= article.title %></h2>
      <p class="excerpt"><%= truncate(article.body, :length => 200) %></p>
      <%= image_tag article.featured_image.url if article.featured_image? %>
    </div>
    <% end %>
    <% end %>

  </div>


</div>

app/views/articles/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>Edit a new article</h2>

		<%= form_for @article do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, class: "form-control", style: "height:600px" %>
		</div>
		<div class="form-group">
			<%= f.label :categories %>
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
		</div>
		<div class="form-group">
			<%= f.label :featured_image %>
			<%= f.file_field :featured_image %>
		</div>

		<%= f.submit "Publish", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/articles/index.html.erb
<div class="col-md-6 col-md-offset-1 pull-left">
    <% @articles.each do |article| %>
    <div class="article">
     <div class="avatar">
      <% if article.user.user_profile != nil %>
        <% if article.user.user_profile.avatar != nil %>
        <%= image_tag article.user.user_profile.avatar.url %>
        <% end %> 
      <% else %>
      <%= image_tag image_url('blank.png')%>    
    <% end %> 

    </div>
     <div class="user-details">
       <p><%= link_to article.user.username.capitalize, user_profile_path(article.user.user_profile) if article.user.user_profile != nil %> in 
           <% article.categories.take(2).each do |category| %>
           <%= link_to category.name, category_path(category) %>
           <% end %>
       </p>
       <p class="sub"><%= article.published_on.strftime("%b %d") if article.published_on? %>
       </p>
   </div>
   <h2><%= link_to article.title, article_path(article) %></h2>
   <p class="excerpt"><%= truncate(article.body, :length => 200) %></p>
   <%= image_tag article.featured_image.url if article.featured_image? %>
   <%= link_to "Read more...", article_path(article.id), class: "read-more" %><br/>
   <%= link_to "#" do %>
   <i class="favorite glyphicon glyphicon-heart-empty"></i>
   <% end %>
</div>
<div class="clearfix"></div>
<% end %>
</div>

<div class="col-md-4">
    <div class="sidebar">
        <h4>Top Stories</h4>
        <ul>
            <% @popular_posts.take(5).each_with_index do |post, i| %>
            <% end %>
        </ul>
    </div>
</div>

app/views/articles/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>Add a new article</h2>

		<%= form_for @article do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, class: "form-control", style: "height:600px" %>
		</div>
		<div class="form-group">
			<%= f.label :categories %>
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
		</div>
		<div class="form-group">
			<%= f.label :featured_image %>
			<%= f.file_field :featured_image %>
		</div>

		<%= f.submit "Publish", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/articles/show.html.erb

<div class="col-md-9 col-md-offset-1">
  <div class="show-article-page">
    <div class="avatar-show">
      <% if @article.user.user_profile != nil %>
      <% if @article.user.user_profile.avatar != nil %>
      <%= image_tag @article.user.user_profile.avatar.url %>
      <% end %> 
      <% else %>
      <%= image_tag image_url('blank.png')%>    
      <% end %> 
    </div>
    <div class="user-details">
    	<p><%= link_to @article.user.username.capitalize, @article.user.user_profile %>
        <p>
          <% if @article.user.user_profile != nil && @article.user.user_profile.tagline != nil%>
          <%= @article.user.user_profile.tagline %></p>
          <% end %>
          <p class="sub"><%= @article.published_on.strftime("%b %d") if @article.published_on? %></p>
        </div>

        <div class="show-article">
         <h2><%= @article.title %></h2>
         <div class="article-body">
          <%= @article.body %>
        </div>
        <ul class="category-list">
          <% @article.categories.each do |category| %>
          <li><%= category.name.capitalize %></li>
          <% end %>
        </ul>

        <div class="user-bio">
          <div class="avatar-show">
            <% if @article.user.user_profile != nil %>
            <% if @article.user.user_profile.avatar != nil %>
            <%= image_tag @article.user.user_profile.avatar.url %>
            <% end %> 
            <% else %>
            <%= image_tag image_url('blank.png')%>    
            <% end %>
          </div>
          <div class="user-details">
           <p><%= link_to @article.user.username.capitalize, @article.user.user_profile %>
              <% if @article.user.user_profile != nil && @article.user.user_profile.bio %>
              <p><%= @article.user.user_profile.bio %></p>
              <% else %>
              <p> No bio</p>
              <% end %>
          </div>
        </div>
      </div>
    </div>
    <%- if user_signed_in? %>
    <b>Comment as <%= current_user.username.capitalize %></b> <br/>
    <%= render partial: 'comments/new' %>
    <% else %>
    <p>Please <%= link_to t('auth.sign_in'), new_user_session_path %> or <%= link_to t('auth.sign_up'), new_user_registration_path %> to add comments</p>
    <% end %>
    <h3>Recent Comments</h3>
    <% if @article.comments.count  >= 1 %>
    <div class="comments">
      <% @article.comments.each do |comment| %>
      <div class="comment">
        <div class="avatar">
          <%= image_tag comment.user.user_profile.avatar.url unless comment.user.blank? %></div>
          <div class="user-details">
            <p><%= comment.body %></p>
            <p><%= comment.user.username unless comment.user.blank? %></p>
            <%- if user_signed_in? %>
            <% if current_user.id == comment.user_id %>
            <div class="pull-right">
              <%= link_to "edit", edit_article_comment_path(@article, comment) %>
            </div>
            <% end %>
            <% end %>


          </div>
        </div>
        <% end %>
        <% end %>
      </div>

app/views/categories/edit.html.erb
<%= form_for @category do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
	<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>
<%= link_to "Add new category", new_category_path %>
<ul>
	<% @categories.each do |category| %>
	<li><%= link_to category.name, category_path(category) %></li>
	<% end %>
</ul>

app/views/categories/new.html.erb
<h2>Add New category </h2>

<%= form_for @category do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit %>
	<% end %>

app/views/categories/show.html.erb
<% @articles.each do |article| %>
<div class="col-md-6 col-md-offset-1">
  <div class="article">
  	<div class="avatar">
      <% if article.user.user_profile != nil %>
      <% if article.user.user_profile.avatar != nil %>
      <%= image_tag article.user.user_profile.avatar.url %>
      <% end %> 
      <% else %>
      <%= image_tag image_url('blank.png')%>    
      <% end %>
    </div>
  	<div class="user-details">
       <p><%= link_to article.user.username.capitalize, current_user %> in 
           <% article.categories.take(2).each do |category| %>
           <%= link_to category.name, category_path(category) %>
           <% end %>
       </p>
       <p class="sub"><%= article.published_on.strftime("%b %d") if article.published_on? %>
       </p>
   </div>
   <h2><%= link_to article.title, article_path(article) %></h2>
   <p class="excerpt"><%= truncate(article.body, :length => 200) %></p>
   <%= image_tag article.featured_image.url if article.featured_image? %>
   <%= link_to "Read more...", article_path, class: "read-more" %><br/>
   <%= link_to "#" do %>
   <i class="favorite glyphicon glyphicon-heart-empty"></i>
   <% end %>
</div>
</div>
<% end %>

app/views/comments/_new.html.erb
<div class="comment-form">
<%= form_for([@article, @article.comments.new]) do |f| %>
	<%= f.text_area :body %><br/>
	<%= f.submit "Submit Comment", class: "btn btn-primary btn-sm" %>
	<% end %>
</div>

app/views/comments/edit.html.erb
<div class="row" style="margin-top: 50px">
	<div class="col-md-5 col-md-offset-3">
		<%= form_for([@article, @comment]) do |f| %>
		<div class="form-group">
			<%= f.text_area :body, class: "form-control", style: "height: 300px" %>
		</div>
		<%= f.submit "Submit Comment", class: "btn btn-primary btn-sm" %>
		<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="main-header">
  <div class="container">

    <div class="top-header">
      <nav class="navbar navbar-default">
        <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag image_url('logo.png') %>
        <% end %>
        
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Write an Article", new_article_path, class: "write" %></li>
          <% if user_signed_in? %>
          <li>
            <% if current_user.user_profile != nil && current_user.user_profile.avatar != nil%>
            <%= image_tag current_user.user_profile.avatar.url, class: "header-avatar" %></li>
            <% else %>
            <%= image_tag image_url('blank.png'), class: "header-avatar" %> 
            <% end %>
            <li><%= link_to current_user.username.capitalize, current_user %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Sign in", new_user_session_path, style: "padding-right:5px" %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>

      <nav class="main-nav">
        <ul class="nav nav-pills">
          <% @categories.each do |category| %>
          <li role="presentation" ><%= link_to category.name,category_path(category.id) %></li>
          <% end %>
        </ul>
      </nav>

    </div>
  </header>

app/views/layouts/_user_settings_menu.html.erb
<div class="user-menu">
	<%= link_to "Write an Article", new_article_path, class: "btn btn-primary" %>
</div>

<ul class="nav nav-pills" style="margin-top:50px; margin-bottom:30px;">
	<li role="presentation" class="<%= 'active' if current_page?(user_path(current_user)) %>"><%= link_to "My Articles", user_path(current_user) %></li>
	<li role="presentation" class="<%= 'active' if current_page?(deleted_articles_path) %>"><%= link_to "Deleted Articles", deleted_articles_path %></li>
	<% if current_user.user_profile != nil %>
		<li role="presentation" class="<%= 'active' if current_page?(edit_user_profile_path(current_user.user_profile.id)) %>"><%= link_to "Edit My Profile", edit_user_profile_path(current_user.user_profile) %></li>
	<% else %>
		<li role="presentation" class="<%= 'active' if current_page?(new_user_profile_path) %>"><%= link_to "Add My Profile", new_user_profile_path %></li>
	<% end %>

	<li role="presentation" class="<%= 'active' if current_page?(edit_user_registration_path) %>"><%= link_to "Account Settings", edit_user_registration_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Publisher</title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag 'application',
	'https://fonts.googleapis.com/css?family=Lora',
	media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body style="background:<%= "#fafafa" if current_page?(root_path) %>">
	<%= render 'layouts/header' %>
	<div class="container">
		<%= alert %>

		<%= notice %>


		<%= yield %>
	</div>
</body>
</html>

app/views/user_profiles/edit.html.erb
<div class="row">
	<div class="col-md-7 col-md-offset-1">
		<%= render partial: 'layouts/user_settings_menu' %>
	</div>

		<div class="col-md-6 col-md-offset-3">
			<%= form_for @userprofile, :html => {:multipart => true} do |f| %>
			<div class="form-group">
				<%= f.label :firstname %>
				<%= f.text_field :first_name, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :last_name %>
				<%= f.text_field :last_name, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :tagline %>
				<%= f.text_field :tagline, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :bio %>
				<%= f.text_area :bio, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :facebook_id %>
				<%= f.text_field :facebook_id, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :twitter_id %>
				<%= f.text_field :twitter_id, class: "form-control" %>
			</div>

			<%= f.file_field :avatar %><br/>

			<%= f.submit "update", class: "btn btn-primary" %>
			<% end %>
		</div>
</div>

app/views/user_profiles/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @userprofile, :html => {:multipart => true} do |f| %>
		<div class="form-group">
			<%= f.label :firstname %>
			<%= f.text_field :first_name, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :last_name %>
			<%= f.text_field :last_name, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :tagline %>
			<%= f.text_field :tagline, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :bio %>
			<%= f.text_area :bio, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :facebook_id %>
			<%= f.text_field :facebook_id, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :twitter_id %>
			<%= f.text_field :twitter_id, class: "form-control" %>
		</div>

		<%= f.file_field :avatar %><br/>

		<%= f.submit "update", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/user_profiles/show.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="user-profile">
        <div class="pull-left">
            <h2><%= @user.first_name %> <%= @user.last_name %></h2>
            <div class="pull-right">
                <div class="avatar-full">
                    <%= image_tag @user.avatar.url if @user.avatar.url %>
                </div>
            </div>
            <p><i><%= @user.tagline %></i></p>
            <p><%= @user.bio %></p>
        </div>
        <div class="clearfix"></div>
    </div>

    <% @user.user.articles.each do |article| %>
    <div class="article">
        <div class="avatar"><%= image_tag article.user.user_profile.avatar.url %></div>
        <div class="user-details">
            <p><%= link_to article.user.username.capitalize, user_profile_path(article.user.user_profile) %> in 
                <% article.categories.take(2).each do |category| %>
                <%= link_to category.name, category_path(category) %>
                <% end %>
            </p>
            <p class="sub"><%= article.published_on.strftime("%b %d") if article.published_on? %>
            </p>
        </div>
        <h2><%= link_to article.title, article_path(article) %></h2>
        <p class="excerpt"><%= truncate(article.body, :length => 200) %></p>
        <%= image_tag article.featured_image.url if article.featured_image? %>
        <%= link_to "Read more...", article_path(article.id), class: "read-more" %><br/>
        <%= link_to "#" do %>
        <i class="favorite glyphicon glyphicon-heart-empty"></i>
        <% end %>
    </div>
    <div class="clearfix"></div>
    <% end %>
</div>

app/views/users/edit.html.erb

<%= form_for @users_profile do |f| %>
	<%= f.label :firstname %><br/>
	<%= f.text_field :first_name %><br/>

	<%= f.label :last_name %><br/>
	<%= f.text_field :last_name %><br/>

	<%= f.label :tagline %><br/>
	<%= f.text_field :tagline %><br/>

	<%= f.label :bio %><br/>
	<%= f.text_are :bio %><br/>

	<%= f.label :facebookid %><br/>
	<%= f.text_field :facebook_id %><br/>

	<%= f.label :twitter_id %><br/>
	<%= f.text_field :twitter_id %><br/>

	<%= f.label :avatar %><br/>
	<%= f.file :avatar %><br/>

	<%= f.submit %>
	<% end %>

app/views/users/new.html.erb
<%= form_for @userprofile do |f| %>
	<%= f.label :first_name %><br/>
	<%= f.text_field :first_name %><br/>
	<%= f.submit %>
	<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-11 col-md-offset-1 pull-left">
    <%= render partial: 'layouts/user_settings_menu' %>
  </div>
  <div class="col-md-6 col-md-offset-1 pull-left">


    <% @user.articles.each do |article| %>
    <div class="article">
      <div class="avatar">
        <% if article.user.user_profile != nil && article.user.user_profile.avatar != nil%>
      <%= image_tag article.user.user_profile.avatar.url %>
      <% else %>
      <%= image_tag image_url('blank.png')%>    
      <% end %>
      </div>
      <div class="user-details">
        <p><%= link_to article.user.username.capitalize, current_user %> in 
          <% article.categories.take(2).each do |category| %>
          <%= link_to category.name, category_path(category) %>
          <% end %>
        </p>
        <p class="sub"><%= article.published_on.strftime("%b %d") if article.published_on? %>
        </p>
      </div>
      <h2><%= link_to article.title, article_path(article) %></h2>
      <p class="excerpt"><%= truncate(article.body, :length => 200) %></p>
      <%= image_tag article.featured_image.url if article.featured_image? %>
      <%= link_to "Read more...", "#", class: "read-more" %><br/>
      <%= link_to edit_article_path, class: "btn btn-default btn-xs pull-right" do %>
      <i class="glyphicon glyphicon-pencil">Edit</i>
      <% end %>
      <%= link_to article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default btn-xs pull-right" do %>
      <i class="glyphicon glyphicon-remove">Delete</i>
      <% end %>
    </div>
    <% end %>

  </div>
<div class="col-md-3 col-md-offset-1 pull-right">
  <h3>Recent Comments</h3>
  <ul class="recent-comments">
  <% @user.articles.each do |article| %>
    <% article.comments.each do |comment| %>
      <li><%= comment.body %><br/>
      <span><%= @analyzer.sentiment comment.body %></span></li>
      <% end %>
  <% end %>
</ul>


</div>

app/views/welcome/index.html.erb
<% @articles.each do |article| %>
<div class="col-md-6 col-md-offset-1">
  <div class="article">
    <p><%= article.user.username %>
    <h2><%= link_to article.title, articles_path %></h2>
    <p><%= truncate(article.body, :length => 200) %></p>
</div>
</div>
<% end %>